public class BANNERAPP{
    public static void main(string[]args)
    {
        System.out.println(String.join(" " ,"   ***   ","   ***   "," ******  ","   *****"));
        System.out.println(String.join(" "," **   ** "," **   ** ","**    ** "," **      "));
        System.out.println(String.join(" ","**     **","**     **","**    ** ","**       "));
        System.out.println(String.join(" ","**     **","**     **","******   ","   ***   "));
        System.out.println(String.join(" ","**     **","**     **","**       ","      ** "));
        System.out.println(String.join(" "," **   ** "," **   ** ","**       ","**     **"));
        System.out.println(String.join(" ","   ***   ","   ***   ","**       "," *****   "));
    }
    
}

